enum ENUM_INDICATOR_SIGNAL
  {
    INDICATOR_SIGNAL_BUY, 
    INDICATOR_SIGNAL_SELL, 
    INDICATOR_SIGNAL_NEUTRAL_ALLOW,
    INDICATOR_SIGNAL_NEUTRAL_BLOCK,
    INDICATOR_FILTER_ALLOW,
    INDICATOR_FILTER_BLOCK,
    
  };
  
enum ENUM_INDICATOR_OPERATION_MODE
  {
   INDICATOR_OPERATION_MODE_IN,  // In
   INDICATOR_OPERATION_MODE_OUT, // Out
   INDICATOR_OPERATION_MODE_BOTH // In/Out
  };